<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IsPackable>true</IsPackable>
    <Description>
      Provides run-time stunt generation using Castle DynamicProxy, for projects that 
      cannot use the compile-time stunt generation built into Stunts, which 
      requires C# 9.0. Installing this package disables compile-time stunts.
    </Description>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Stunt.*.*" />
    <None Include="Stunt.*.*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Castle.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Stunts\Stunts.csproj" Pack="false" />
    <ProjectReference Include="..\Stunts.Package\Stunts.Package.msbuildproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
  
  <ItemGroup>
    <None Update="Stunt.*.*;*.props;*.targets" PackFolder="build\netstandard2.0" />
    <PackageFile Include="Stunt.*.*;*.props;*.targets" PackFolder="buildTransitive\netstandard2.0" />
  </ItemGroup>

</Project>
