<Project>

  <ItemGroup Condition="'$(EnableCompileTimeStunts)' != 'true'">
    <Compile Include="$(MSBuildThisFileDirectory)Stunt.DynamicFactory$(DefaultLanguageSourceExtension)"
             Condition="Exists('$(MSBuildThisFileDirectory)Stunt.DynamicFactory$(DefaultLanguageSourceExtension)')"
             Visible="false" />
  </ItemGroup>

</Project>