<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
    <PublishAot>true</PublishAot>
    <EnableCompileTimeStunts>true</EnableCompileTimeStunts>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors>$(WarningsAsErrors);IL2026;IL3050;ST015</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Stunts" />
  </ItemGroup>

</Project>
