' <auto-generated>
'     This code was included from Stunts.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>

Imports System
Imports System.Collections.Generic
Imports System.Diagnostics.CodeAnalysis
Imports System.Reflection
Imports System.Runtime.CompilerServices

Namespace Global.Stunts

    ''' <summary>
    ''' Holds a reference to a stunt of type <typeparamref name="T"/>, exposing its
    ''' <see cref="Behaviors"/> for configuration, and allowing conversion to
    ''' <typeparamref name="T"/> via <see cref="ToObject"/>.
    ''' </summary>
    ''' <remarks>
    ''' When constructed from a <see cref="Lazy(Of T)"/>, the stunt is created on the first
    ''' <see cref="ToObject"/> call. Behaviors added before that call initialize the pipeline
    ''' used during construction, including virtual members invoked from a base constructor,
    ''' via <see cref="BehaviorPipelineFactory.UseAmbient"/>. If none were added, the factory
    ''' already current at that call is used.
    ''' The widening conversion calls <see cref="ToObject"/>.
    ''' </remarks>
    <CompilerGenerated>
    <ExcludeFromCodeCoverage>
    Partial Friend Class StuntReference(Of T)
        Implements IStunt

        Private ReadOnly lazy As Lazy(Of T)
        ' Behaviors configured before the stunt exists. Construction copies them into the pipeline.
        Private ReadOnly behaviorList As IList(Of IStuntBehavior) = New List(Of IStuntBehavior)()
        Private stunt As IStunt

        ''' <summary>
        ''' Initializes a new instance of <see cref="StuntReference(Of T)"/> that constructs the stunt
        ''' on the first <see cref="ToObject"/> call.
        ''' </summary>
        ''' <param name="value">The deferred stunt of type <typeparamref name="T"/>.</param>
        ''' <exception cref="ArgumentNullException">Thrown when <paramref name="value"/> is <see langword="Nothing"/>.</exception>
        Public Sub New(ByVal value As Lazy(Of T))
            If value Is Nothing Then
                Throw New ArgumentNullException(NameOf(value))
            End If

            lazy = value
        End Sub

        ''' <summary>
        ''' Initializes a new instance of <see cref="StuntReference(Of T)"/> for an already constructed stunt.
        ''' </summary>
        ''' <param name="value">The stunt of type <typeparamref name="T"/> to reference.</param>
        ''' <exception cref="ArgumentException">Thrown when the value does not implement <see cref="IStunt"/>.</exception>
        Public Sub New(ByVal value As T)
            Me.New(New Lazy(Of T)(Function() value))
            ' Construction already happened, so behaviors apply to the live instance immediately.
            stunt = Unwrap(value)
        End Sub

        ''' <summary>
        ''' Gets the behaviors associated with the referenced stunt.
        ''' </summary>
        ''' <remarks>
        ''' Before the stunt is constructed, this is the list that seeds its pipeline.
        ''' Afterwards it is the stunt's own behavior list.
        ''' </remarks>
        Public ReadOnly Property Behaviors As IList(Of IStuntBehavior) Implements IStunt.Behaviors
            Get
                If stunt Is Nothing Then
                    Return behaviorList
                End If

                Return stunt.Behaviors
            End Get
        End Property

        ''' <summary>
        ''' Gets the referenced stunt of type <typeparamref name="T"/>, constructing it on the first call.
        ''' </summary>
        Public Function ToObject() As T
            If stunt Is Nothing Then
                ' Capture the current factory first: the ambient scope below hides it,
                ' and an unconfigured reference should still construct with that factory.
                Dim fallback = BehaviorPipelineFactory.Default
                Using BehaviorPipelineFactory.UseAmbient(New ReferencePipelineFactory(behaviorList, fallback))
                    Dim created = lazy.Value
                    Dim resolved = Unwrap(created)
                    ' Dynamic proxies create their pipeline on the first intercept, which includes this getter.
                    EnsurePipeline(resolved)
                    stunt = resolved
                    Return created
                End Using
            End If

            Return lazy.Value
        End Function

        ''' <summary>
        ''' Allows implicit conversion from <see cref="StuntReference(Of T)"/> to <typeparamref name="T"/>.
        ''' </summary>
        Public Shared Widening Operator CType(ByVal stunt As StuntReference(Of T)) As T
            Return stunt.ToObject()
        End Operator

        Private Shared Function Unwrap(ByVal value As T) As IStunt
            ' A delegate stunt is the bound delegate; its target is the generated instance.
            Dim instance = TryCast(DirectCast(value, Object), IStunt)
            If instance Is Nothing Then
                Dim target = TryCast(DirectCast(value, Object), [Delegate])
                If target IsNot Nothing Then
                    instance = TryCast(target.Target, IStunt)
                End If
            End If

            If instance Is Nothing Then
                Throw New ArgumentException($"Value of type {GetType(T)} does not implement IStunt.", NameOf(value))
            End If

            Return instance
        End Function

        Private Shared Sub EnsurePipeline(ByVal instance As IStunt)
            Dim unused = instance.Behaviors
        End Sub

        Private Class ReferencePipelineFactory
            Implements IBehaviorPipelineFactory

            Private ReadOnly behaviors As IList(Of IStuntBehavior)
            Private ReadOnly fallback As IBehaviorPipelineFactory

            Public Sub New(ByVal behaviors As IList(Of IStuntBehavior), ByVal fallback As IBehaviorPipelineFactory)
                Me.behaviors = behaviors
                Me.fallback = fallback
            End Sub

            Public Function CreatePipeline(Of TStunt)() As BehaviorPipeline Implements IBehaviorPipelineFactory.CreatePipeline
                If behaviors.Count = 0 Then
                    Return fallback.CreatePipeline(Of TStunt)()
                End If

                Return New BehaviorPipeline(behaviors)
            End Function
        End Class
    End Class

    ''' <summary>
    ''' Builds stunts that all share the same set of <see cref="Behaviors"/>, which are 
    ''' applied from the very beginning of the stunt instantiation, including any virtual 
    ''' members invoked from a base class constructor.
    ''' </summary>
    ''' <remarks>
    ''' Behaviors are configured with the same <c>AddBehavior</c>/<c>InsertBehavior</c> 
    ''' extension methods available for any <see cref="IStunt"/>, and each <c>Build</c> 
    ''' call creates the stunt with a pipeline initialized with a snapshot of the 
    ''' behaviors configured at that point, via <see cref="BehaviorPipelineFactory.UseAmbient"/>.
    ''' </remarks>
    <CompilerGenerated>
    <ExcludeFromCodeCoverage>
    Partial Friend Class StuntBuilder
        Implements IStunt

        ''' <summary>
        ''' Behaviors applied to every stunt created by this builder.
        ''' </summary>
        Public ReadOnly Property Behaviors As IList(Of IStuntBehavior) Implements IStunt.Behaviors
            Get
                Return behaviorList
            End Get
        End Property

        Private ReadOnly behaviorList As IList(Of IStuntBehavior) = New List(Of IStuntBehavior)

        Private Function Create(Of T)(ByVal constructorArgs As Object(), ParamArray interfaces As Type()) As T
            Using BehaviorPipelineFactory.UseAmbient(New BuilderPipelineFactory(behaviorList))
                Return DirectCast(StuntFactory.[Default].CreateStunt(GetType(Stunt).Assembly, GetType(T), interfaces, constructorArgs), T)
            End Using
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements the type <typeparamref name="T"/>.
        ''' </summary>
        <StuntGenerator>
        Public Function Build(Of T)(ParamArray constructorArgs As Object()) As T
            Return Create(Of T)(constructorArgs)
        End Function

        ''' <summary>
        ''' Creates a stunt for the delegate <typeparamref name="T"/> that forwards to
        ''' <paramref name="implementation"/>. The builder behaviors run first;
        ''' <c>next</c> invokes <paramref name="implementation"/>.
        ''' </summary>
        ''' <remarks>
        ''' Unlike C#, Visual Basic cannot constrain <typeparamref name="T"/> to be a delegate, 
        ''' so this overload is also a candidate for a single constructor argument of type 
        ''' <typeparamref name="T"/>, which behaves identically.
        ''' </remarks>
        <StuntGenerator>
        Public Function Build(Of T)(ByVal implementation As T) As T
            If implementation Is Nothing Then
                Throw New ArgumentNullException(NameOf(implementation))
            End If

            Return Create(Of T)(New Object() {implementation})
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>.
        ''' </summary>
        <StuntGenerator>
        Public Function Build(Of T, T1)(ParamArray constructorArgs As Object()) As T
            Return Create(Of T)(constructorArgs, GetType(T1))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/> and <typeparamref name="T2"/>.
        ''' </summary>
        <StuntGenerator>
        Public Function Build(Of T, T1, T2)(ParamArray constructorArgs As Object()) As T
            Return Create(Of T)(constructorArgs, GetType(T1), GetType(T2))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>, <typeparamref name="T2"/> and 
        ''' <typeparamref name="T3"/>.
        ''' </summary>
        <StuntGenerator>
        Public Function Build(Of T, T1, T2, T3)(ParamArray constructorArgs As Object()) As T
            Return Create(Of T)(constructorArgs, GetType(T1), GetType(T2), GetType(T3))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>, <typeparamref name="T2"/>, 
        ''' <typeparamref name="T3"/> and <typeparamref name="T4"/>.
        ''' </summary>
        <StuntGenerator>
        Public Function Build(Of T, T1, T2, T3, T4)(ParamArray constructorArgs As Object()) As T
            Return Create(Of T)(constructorArgs, GetType(T1), GetType(T2), GetType(T3), GetType(T4))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>, <typeparamref name="T2"/>, 
        ''' <typeparamref name="T3"/>, <typeparamref name="T4"/> and <typeparamref name="T5"/>.
        ''' </summary>
        <StuntGenerator>
        Public Function Build(Of T, T1, T2, T3, T4, T5)(ParamArray constructorArgs As Object()) As T
            Return Create(Of T)(constructorArgs, GetType(T1), GetType(T2), GetType(T3), GetType(T4), GetType(T5))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>, <typeparamref name="T2"/>, 
        ''' <typeparamref name="T3"/>, <typeparamref name="T4"/>, <typeparamref name="T5"/> 
        ''' and <typeparamref name="T6"/>.
        ''' </summary>
        <StuntGenerator>
        Public Function Build(Of T, T1, T2, T3, T4, T5, T6)(ParamArray constructorArgs As Object()) As T
            Return Create(Of T)(constructorArgs, GetType(T1), GetType(T2), GetType(T3), GetType(T4), GetType(T5), GetType(T6))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>, <typeparamref name="T2"/>, 
        ''' <typeparamref name="T3"/>, <typeparamref name="T4"/>, <typeparamref name="T5"/> 
        ''' <typeparamref name="T6"/> and <typeparamref name="T7"/>.
        ''' </summary>
        <StuntGenerator>
        Public Function Build(Of T, T1, T2, T3, T4, T5, T6, T7)(ParamArray constructorArgs As Object()) As T
            Return Create(Of T)(constructorArgs, GetType(T1), GetType(T2), GetType(T3), GetType(T4), GetType(T5), GetType(T6), GetType(T7))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>, <typeparamref name="T2"/>, 
        ''' <typeparamref name="T3"/>, <typeparamref name="T4"/>, <typeparamref name="T5"/> 
        ''' <typeparamref name="T6"/>, <typeparamref name="T7"/> and <typeparamref name="T8"/>.
        ''' </summary>
        <StuntGenerator>
        Public Function Build(Of T, T1, T2, T3, T4, T5, T6, T7, T8)(ParamArray constructorArgs As Object()) As T
            Return Create(Of T)(constructorArgs, GetType(T1), GetType(T2), GetType(T3), GetType(T4), GetType(T5), GetType(T6), GetType(T7), GetType(T8))
        End Function

        Private Class BuilderPipelineFactory
            Implements IBehaviorPipelineFactory

            Private ReadOnly behaviors As IEnumerable(Of IStuntBehavior)

            Public Sub New(ByVal behaviors As IEnumerable(Of IStuntBehavior))
                Me.behaviors = behaviors
            End Sub

            ' The pipeline copies the behaviors, so later builder changes don't affect created stunts.
            Public Function CreatePipeline(Of TStunt)() As BehaviorPipeline Implements IBehaviorPipelineFactory.CreatePipeline
                Return New BehaviorPipeline(behaviors)
            End Function
        End Class
    End Class

    ''' <summary>
    ''' Instantiates stunts for the specified types.
    ''' </summary>
    <CompilerGenerated>
    <ExcludeFromCodeCoverage>
    Partial Friend Class Stunt
        Private Shared Function Create(Of T)(ByVal constructorArgs As Object(), ParamArray interfaces As Type()) As T
            Return DirectCast(StuntFactory.[Default].CreateStunt(GetType(Stunt).Assembly, GetType(T), interfaces, constructorArgs), T)
        End Function

        Private Shared Function Defer(Of TResult)(ByVal factory As Func(Of TResult)) As StuntReference(Of TResult)
            Return New StuntReference(Of TResult)(New Lazy(Of TResult)(factory))
        End Function

        ''' <summary>
        ''' Creates a <see cref="StuntBuilder"/> that applies the same behaviors to every 
        ''' stunt it builds, from the moment of their instantiation.
        ''' </summary>
        Public Shared Function Builder() As StuntBuilder
            Return New StuntBuilder()
        End Function

        ''' <summary>
        ''' Gets a reference to an existing stunt, so behaviors can be added to it after the fact.
        ''' </summary>
        ''' <param name="stunt">An existing stunt, typically created via one of the <c>Of</c> overloads.</param>
        ''' <exception cref="ArgumentException">Thrown when the value does not implement <see cref="IStunt"/>.</exception>
        Public Shared Function [Get](Of T)(ByVal stunt As T) As StuntReference(Of T)
            Return New StuntReference(Of T)(stunt)
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements the type <typeparamref name="T"/>.
        ''' </summary>
        <StuntGenerator>
        Public Shared Function [Of](Of T)(ParamArray constructorArgs As Object()) As T
            Return Create(Of T)(constructorArgs)
        End Function

        ''' <summary>
        ''' Creates a stunt for the delegate <typeparamref name="T"/> that forwards to
        ''' <paramref name="implementation"/>. Behaviors added afterwards run first;
        ''' <c>next</c> invokes <paramref name="implementation"/>.
        ''' </summary>
        ''' <remarks>
        ''' Unlike C#, Visual Basic cannot constrain <typeparamref name="T"/> to be a delegate, 
        ''' so this overload is also a candidate for a single constructor argument of type 
        ''' <typeparamref name="T"/>, which behaves identically.
        ''' </remarks>
        <StuntGenerator>
        Public Shared Function [Of](Of T)(ByVal implementation As T) As T
            If implementation Is Nothing Then
                Throw New ArgumentNullException(NameOf(implementation))
            End If

            Return Create(Of T)(New Object() {implementation})
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>.
        ''' </summary>
        <StuntGenerator>
        Public Shared Function [Of](Of T, T1)(ParamArray constructorArgs As Object()) As T
            Return Create(Of T)(constructorArgs, GetType(T1))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/> and <typeparamref name="T2"/>.
        ''' </summary>
        <StuntGenerator>
        Public Shared Function [Of](Of T, T1, T2)(ParamArray constructorArgs As Object()) As T
            Return Create(Of T)(constructorArgs, GetType(T1), GetType(T2))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>, <typeparamref name="T2"/> and 
        ''' <typeparamref name="T3"/>.
        ''' </summary>
        <StuntGenerator>
        Public Shared Function [Of](Of T, T1, T2, T3)(ParamArray constructorArgs As Object()) As T
            Return Create(Of T)(constructorArgs, GetType(T1), GetType(T2), GetType(T3))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>, <typeparamref name="T2"/>, 
        ''' <typeparamref name="T3"/> and <typeparamref name="T4"/>.
        ''' </summary>
        <StuntGenerator>
        Public Shared Function [Of](Of T, T1, T2, T3, T4)(ParamArray constructorArgs As Object()) As T
            Return Create(Of T)(constructorArgs, GetType(T1), GetType(T2), GetType(T3), GetType(T4))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>, <typeparamref name="T2"/>, 
        ''' <typeparamref name="T3"/>, <typeparamref name="T4"/> and <typeparamref name="T5"/>.
        ''' </summary>
        <StuntGenerator>
        Public Shared Function [Of](Of T, T1, T2, T3, T4, T5)(ParamArray constructorArgs As Object()) As T
            Return Create(Of T)(constructorArgs, GetType(T1), GetType(T2), GetType(T3), GetType(T4), GetType(T5))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>, <typeparamref name="T2"/>, 
        ''' <typeparamref name="T3"/>, <typeparamref name="T4"/>, <typeparamref name="T5"/> 
        ''' and <typeparamref name="T6"/>.
        ''' </summary>
        <StuntGenerator>
        Public Shared Function [Of](Of T, T1, T2, T3, T4, T5, T6)(ParamArray constructorArgs As Object()) As T
            Return Create(Of T)(constructorArgs, GetType(T1), GetType(T2), GetType(T3), GetType(T4), GetType(T5), GetType(T6))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>, <typeparamref name="T2"/>, 
        ''' <typeparamref name="T3"/>, <typeparamref name="T4"/>, <typeparamref name="T5"/> 
        ''' <typeparamref name="T6"/> and <typeparamref name="T7"/>.
        ''' </summary>
        <StuntGenerator>
        Public Shared Function [Of](Of T, T1, T2, T3, T4, T5, T6, T7)(ParamArray constructorArgs As Object()) As T
            Return Create(Of T)(constructorArgs, GetType(T1), GetType(T2), GetType(T3), GetType(T4), GetType(T5), GetType(T6), GetType(T7))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>, <typeparamref name="T2"/>, 
        ''' <typeparamref name="T3"/>, <typeparamref name="T4"/>, <typeparamref name="T5"/> 
        ''' <typeparamref name="T6"/>, <typeparamref name="T7"/> and <typeparamref name="T8"/>.
        ''' </summary>
        <StuntGenerator>
        Public Shared Function [Of](Of T, T1, T2, T3, T4, T5, T6, T7, T8)(ParamArray constructorArgs As Object()) As T
            Return Create(Of T)(constructorArgs, GetType(T1), GetType(T2), GetType(T3), GetType(T4), GetType(T5), GetType(T6), GetType(T7), GetType(T8))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements the type <typeparamref name="T"/>, 
        ''' returning a reference to it that allows configuring its behaviors.
        ''' The instance is constructed on the first <see cref="StuntReference(Of T).ToObject"/> call.
        ''' </summary>
        <StuntGenerator>
        Public Shared Function [For](Of T)(ParamArray constructorArgs As Object()) As StuntReference(Of T)
            Return Defer(Function() Create(Of T)(constructorArgs))
        End Function

        ''' <summary>
        ''' Creates a stunt for the delegate <typeparamref name="T"/> that forwards to
        ''' <paramref name="implementation"/>, returning a reference to it that allows 
        ''' configuring its behaviors. Behaviors added afterwards run first; 
        ''' <c>next</c> invokes <paramref name="implementation"/>.
        ''' </summary>
        ''' <remarks>
        ''' Unlike C#, Visual Basic cannot constrain <typeparamref name="T"/> to be a delegate, 
        ''' so this overload is also a candidate for a single constructor argument of type 
        ''' <typeparamref name="T"/>, which behaves identically.
        ''' </remarks>
        <StuntGenerator>
        Public Shared Function [For](Of T)(ByVal implementation As T) As StuntReference(Of T)
            If implementation Is Nothing Then
                Throw New ArgumentNullException(NameOf(implementation))
            End If

            Return Defer(Function() Create(Of T)(New Object() {implementation}))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>, returning a reference 
        ''' to it that allows configuring its behaviors.
        ''' </summary>
        <StuntGenerator>
        Public Shared Function [For](Of T, T1)(ParamArray constructorArgs As Object()) As StuntReference(Of T)
            Return Defer(Function() Create(Of T)(constructorArgs, GetType(T1)))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/> and <typeparamref name="T2"/>, 
        ''' returning a reference to it that allows configuring its behaviors.
        ''' </summary>
        <StuntGenerator>
        Public Shared Function [For](Of T, T1, T2)(ParamArray constructorArgs As Object()) As StuntReference(Of T)
            Return Defer(Function() Create(Of T)(constructorArgs, GetType(T1), GetType(T2)))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>, <typeparamref name="T2"/> and 
        ''' <typeparamref name="T3"/>, returning a reference to it that allows configuring its behaviors.
        ''' </summary>
        <StuntGenerator>
        Public Shared Function [For](Of T, T1, T2, T3)(ParamArray constructorArgs As Object()) As StuntReference(Of T)
            Return Defer(Function() Create(Of T)(constructorArgs, GetType(T1), GetType(T2), GetType(T3)))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>, <typeparamref name="T2"/>, 
        ''' <typeparamref name="T3"/> and <typeparamref name="T4"/>, returning a reference 
        ''' to it that allows configuring its behaviors.
        ''' </summary>
        <StuntGenerator>
        Public Shared Function [For](Of T, T1, T2, T3, T4)(ParamArray constructorArgs As Object()) As StuntReference(Of T)
            Return Defer(Function() Create(Of T)(constructorArgs, GetType(T1), GetType(T2), GetType(T3), GetType(T4)))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>, <typeparamref name="T2"/>, 
        ''' <typeparamref name="T3"/>, <typeparamref name="T4"/> and <typeparamref name="T5"/>, 
        ''' returning a reference to it that allows configuring its behaviors.
        ''' </summary>
        <StuntGenerator>
        Public Shared Function [For](Of T, T1, T2, T3, T4, T5)(ParamArray constructorArgs As Object()) As StuntReference(Of T)
            Return Defer(Function() Create(Of T)(constructorArgs, GetType(T1), GetType(T2), GetType(T3), GetType(T4), GetType(T5)))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>, <typeparamref name="T2"/>, 
        ''' <typeparamref name="T3"/>, <typeparamref name="T4"/>, <typeparamref name="T5"/> 
        ''' and <typeparamref name="T6"/>, returning a reference to it that allows configuring its behaviors.
        ''' </summary>
        <StuntGenerator>
        Public Shared Function [For](Of T, T1, T2, T3, T4, T5, T6)(ParamArray constructorArgs As Object()) As StuntReference(Of T)
            Return Defer(Function() Create(Of T)(constructorArgs, GetType(T1), GetType(T2), GetType(T3), GetType(T4), GetType(T5), GetType(T6)))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>, <typeparamref name="T2"/>, 
        ''' <typeparamref name="T3"/>, <typeparamref name="T4"/>, <typeparamref name="T5"/> 
        ''' <typeparamref name="T6"/> and <typeparamref name="T7"/>, returning a reference 
        ''' to it that allows configuring its behaviors.
        ''' </summary>
        <StuntGenerator>
        Public Shared Function [For](Of T, T1, T2, T3, T4, T5, T6, T7)(ParamArray constructorArgs As Object()) As StuntReference(Of T)
            Return Defer(Function() Create(Of T)(constructorArgs, GetType(T1), GetType(T2), GetType(T3), GetType(T4), GetType(T5), GetType(T6), GetType(T7)))
        End Function

        ''' <summary>
        ''' Creates a stunt that inherits or implements <typeparamref name="T"/> and 
        ''' additionally implements <typeparamref name="T1"/>, <typeparamref name="T2"/>, 
        ''' <typeparamref name="T3"/>, <typeparamref name="T4"/>, <typeparamref name="T5"/> 
        ''' <typeparamref name="T6"/>, <typeparamref name="T7"/> and <typeparamref name="T8"/>, 
        ''' returning a reference to it that allows configuring its behaviors.
        ''' </summary>
        <StuntGenerator>
        Public Shared Function [For](Of T, T1, T2, T3, T4, T5, T6, T7, T8)(ParamArray constructorArgs As Object()) As StuntReference(Of T)
            Return Defer(Function() Create(Of T)(constructorArgs, GetType(T1), GetType(T2), GetType(T3), GetType(T4), GetType(T5), GetType(T6), GetType(T7), GetType(T8)))
        End Function
    End Class
End Namespace

