// <auto-generated>
//     This code was included from Stunts.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace Stunts
{
    partial class Stunt
    {
        static Stunt()
        {
            StuntFactory.Default = new StaticStuntFactory();
            OnInitialized();
        }

        /// <summary>
        /// Invoked after the default <see cref="StuntFactory.Default"/> 
        /// is initialized.
        /// </summary>
        static partial void OnInitialized();
    }
}
