name: pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - pages
      - docs

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v4

      - name: ⚙ jekyll
        run: |
          sudo gem install bundler
          sudo bundle install

      - name: 🖉 repo
        run: echo "REPOSITORY=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: 🙏 build
        run: bundle exec jekyll build -b ${{ env.REPOSITORY }}
        env:
          JEKYLL_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ✓ commit
        run: |
          cd _site
          git init
          git add -A
          git config --local user.email "hello@clarius.org"
          git config --local user.name "GitHub Action"
          git commit -m "Publish pages from ${GITHUB_REPOSITORY}@${GITHUB_SHA:0:9}"

      - name: 🚀 push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.CLARIUS_ACCESS_TOKEN }}
          repository: clarius/${{ env.REPOSITORY }}
          branch: gh-pages
          force: true
          directory: ./_site