# Builds a final release version and pushes to nuget.org 
# whenever a release is published.
# Requires: secrets.NUGET_API_KEY

name: publish
on:
  release:
    types: [prereleased, released]

env:
  DOTNET_NOLOGO: true
  Configuration: Release

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 🤘 checkout
        uses: actions/checkout@v4
        with: 
          submodules: recursive
          fetch-depth: 0

      - name: ⚙ dotnet
        uses: devlooped/actions-dotnet-env@v1

      - name: 🙏 build
        run: dotnet build -m:1 -bl:build.binlog -p:version=${GITHUB_REF#refs/*/v} -p:RepositoryBranch=${GITHUB_REF#refs/*/}

      - name: 🧪 test
        run: dotnet test --no-build -m:1

      - name: 📦 pack
        run: dotnet pack -m:1 -bl:pack.binlog -p:version=${GITHUB_REF#refs/*/v} -p:RepositoryBranch=${GITHUB_REF#refs/*/}

      - name: 🔼 logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        if: runner.debug && always()
        with:
          name: logs
          path: '*.binlog'

      - name: ✅ validate
        shell: pwsh
        working-directory: bin
        run: |
          $invalid = Get-ChildItem -File -Filter "*.42.42*.nupkg"
          if ($invalid) {
            Write-Error "Found dev/local packages with disallowed 42.42* version prefix:`n$($invalid.Name -join "`n")"
            exit 1
          }

      - name: 🚀 nuget
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        if: ${{ env.NUGET_API_KEY != '' && github.event.action != 'prereleased' }}
        run: dotnet nuget push ./bin/**/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
